### ISSUE TITLE
ocp_install_env.sh no longer works

### ISSUE THREAD

**Issue by hardys** [imain/ocp-doit#33]
All of the environment variables have been removed from the installer, so we're not forced to answer everything interactively.

I think we need to move to the installconfig yaml format instead, but not looked into the details yet.

**Comment by trown** [comment]
The CI handled this by heredoc'ing an install-config.yaml from the env vars: https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml#L299-L362

I can put up a patch to do something similar here.

**Comment by trown** [comment]
fixed by https://github.com/imain/ocp-doit/pull/34
