### ISSUE TITLE
Deploying with designate is broken

### ISSUE THREAD

**Issue by hardys** [imain/ocp-doit#8]
Reported by apuimedo that deploying breaks with an error about missing DesignatePools like:

2018-11-23 14:56:07Z [standalone.StandaloneServiceChain.ServiceChain.15]: CREATE_FAILED  StackValidationFailed: resources[15]: Property error: resources.DesignateCentralBase.properties: Property DesignatePools not assigned

I think it's due to this commit:
https://github.com/openstack/tripleo-heat-templates/commit/3abb38ae149640efe1821c82094ed20dbd390c24

So we either need to disable designate or pass a valid config like this sample:
https://github.com/openstack/tripleo-heat-templates/blob/master/environments/designate-config.yaml

**Comment by tomassedovic** [comment]
As far as I'm concerned, it's okay if we drop it for now. We're not actually using it for anything right now.
